### ISSUE TITLE
The objloader2 show only the last mesh from the group

### ISSUE THREAD

**Issue by George35mk** [kaisalmen/WWOBJLoader#40] opened 2018-04-16 18:21 UTC
Thanks for this beautiful lib Kaisalmen''

I need your help I stack with the objloader2 

when I try to load a .obj file were I have a group that have 21 children meshes I cant access the meshes only print me this output

I have this code to load the group

```Typescript

loadLargeOBJ() {

    const loader = new THREE.OBJLoader2();

    const callbackOnLoad = ( event ) => {

      this.view.scene.add( event.detail.loaderRootNode );

      const group = event.detail.loaderRootNode;

      this.renderer.render(this.scene, this.camera);
    };

    // load a resource from provided URL synchronously
    const asynchromus = true;
    loader.load( '../../../assets/models/brain.obj', callbackOnLoad, null, null, null, asynchromus );
    loader.loadMTL('../../../assets/models/brain.mtl');
  }
```

```
Material with name "defaultMaterial" will be added.
21:20:24.657 Three.es.js:60680 Material with name "defaultVertexColorMaterial" will be added.
21:20:24.658 Three.es.js:60680 Material with name "defaultLineMaterial" will be added.
21:20:24.668 Three.es.js:60680 Material with name "defaultPointMaterial" will be added.
21:20:24.668 Three.es.js:60990 WorkerSupport: Building worker code...
21:20:24.668 Three.es.js:61001 WorkerSupport: Using DEFAULT "LoaderSupport.WorkerRunnerRefImpl" as Runner class for worker.
21:20:24.678 Three.es.js:61040 buildWebWorkerCode: 10.19921875ms
21:20:24.744 blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:139 OBJLoader2.Parser configuration:
	materialNames:
		- defaultMaterial
		- defaultVertexColorMaterial
		- defaultLineMaterial
		- defaultPointMaterial
	useAsync: true
	materialPerSmoothingGroup: false
	useIndices: false
	disregardNormals: false
	callbackMeshBuilderName: callbackMeshBuilder
	callbackProgressName: callbackProgress
21:20:27.893 blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:820 Global output object count: 1
21:20:27.910 blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672 object_group "3rd-Ventricle_Cube.053_" was defined with unresolvable material "3rd_ventricle_material"! Assigning "defaultMaterial".
Parser.buildMesh @ blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672
21:20:27.912 blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672 object_group "4th_ventricle_Cube.052_" was defined with unresolvable material "4th_ventricle_material"! Assigning "defaultMaterial".
Parser.buildMesh @ blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672
21:20:27.914 blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672 object_group "Amygdala_Cube.031_" was defined with unresolvable material "amigdala_material"! Assigning "defaultMaterial".
Parser.buildMesh @ blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672
21:20:27.915 blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672 object_group "Caudate_Cube.049_" was defined with unresolvable material "caudate_material"! Assigning "defaultMaterial".
Parser.buildMesh @ blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672
21:20:27.915 blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672 object_group "Fornix_Cube.048_" was defined with unresolvable material "fornix_material"! Assigning "defaultMaterial".
Parser.buildMesh @ blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672
21:20:27.916 blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672 object_group "Group47710.001_" was defined with unresolvable material "cerebellum_material"! Assigning "defaultMaterial".
Parser.buildMesh @ blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672
21:20:27.917 blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672 object_group "hemi_left_ZBrush_defualt_group.002_" was defined with unresolvable material "left_hemi_material"! Assigning "defaultMaterial".
Parser.buildMesh @ blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672
21:20:27.920 blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672 object_group "hemi_right_ZBrush_defualt_group.003_" was defined with unresolvable material "right_hemi_material"! Assigning "defaultMaterial".
Parser.buildMesh @ blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672
21:20:27.926 blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672 object_group "Hipophisys_Cube.046_" was defined with unresolvable material "hypophisis"! Assigning "defaultMaterial".
Parser.buildMesh @ blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672
21:20:27.927 blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672 object_group "Hippocampus_Cube.044_" was defined with unresolvable material "hyppocampus_material"! Assigning "defaultMaterial".
Parser.buildMesh @ blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672
21:20:27.928 blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672 object_group "Lateral-Ventricle_Cube.047_" was defined with unresolvable material "lateral_ventricle_material"! Assigning "defaultMaterial".
Parser.buildMesh @ blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672
21:20:27.928 blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672 object_group "Medulla_oblongata_Cube.045_" was defined with unresolvable material "medulla_material.001"! Assigning "defaultMaterial".
Parser.buildMesh @ blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672
21:20:27.930 blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672 object_group "Middle_brain_Pedunculis__Cube.051_" was defined with unresolvable material "middle_brain_material"! Assigning "defaultMaterial".
Parser.buildMesh @ blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672
21:20:27.932 blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672 object_group "Nervus_Olphactorius_Cube.057_" was defined with unresolvable material "nervus_olphactorius_material.001"! Assigning "defaultMaterial".
Parser.buildMesh @ blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672
21:20:27.933 blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672 object_group "Nervus_Ophtalmicus_Cube.055_" was defined with unresolvable material "ophtalmicus_material.001"! Assigning "defaultMaterial".
Parser.buildMesh @ blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672
21:20:27.934 blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672 object_group "Nucleus_Accumbens_Cube.056_" was defined with unresolvable material "accumbens.002"! Assigning "defaultMaterial".
Parser.buildMesh @ blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672
21:20:27.936 blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672 object_group "Pallidum_Cube.054_" was defined with unresolvable material "accumbens"! Assigning "defaultMaterial".
Parser.buildMesh @ blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672
21:20:27.936 blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672 object_group "Putamen_Cube.043_" was defined with unresolvable material "putamen_material.001"! Assigning "defaultMaterial".
Parser.buildMesh @ blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672
21:20:27.937 blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672 object_group "Thalamus_Cube.050_" was defined with unresolvable material "Thalamus_material.001"! Assigning "defaultMaterial".
Parser.buildMesh @ blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672
21:20:27.938 blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672 object_group "white_left_ZBrush_defualt_group.001_" was defined with unresolvable material "defaultMat"! Assigning "defaultMaterial".
Parser.buildMesh @ blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:672
21:20:28.111 blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:827 Overall counts: 
	Vertices: 1339986
	Faces: 1339986
	Multiple definitions: 0
21:20:28.112 blob:http://localhost:4200/f6f8196b-267f-4e42-9928-62b726551ceb:886 WorkerRunner: Run complete!
```

**Comment by George35mk** [comment] 2018-04-17 07:41
Can you show me please how i can access the meshes individual one by one

Στις Δευ, 16 Απρ 2018, 11:24 μ.μ. ο χρήστης Kai Salmen <
notifications@github.com> έγραψε:

**Comment by George35mk** [comment] 2018-04-17 08:05
And one more if you have the time is tos ahow me how i can load multiple .obj filea asynchronus thats only .

Thank you.
George35mk

**Comment by kaisalmen** [comment] 2018-04-17 19:32
@George35mk scene traversal after loading is done is independent of `OBJLoader2`, but if you want to alter a mesh once it becomes available use the `onMeshAlter` callback you can pass on to load:
```javascript
loader.load( '../../../assets/models/brain.obj', callbackOnLoad, null, null, callbackOnMeshAlter, asynchromus );
```
See how the function shall be used here:
https://github.com/kaisalmen/WWOBJLoader/blob/master/test/wwobjloader2/WWOBJLoader2Example.js#L226-L240

Loading multiple OBJs with a number of workers is done here:
https://github.com/kaisalmen/WWOBJLoader/tree/master/test/wwparallels

Hope this helps.

I don't consider this a bug and will close this issue.

**Comment by George35mk** [comment] 2018-04-17 23:39
Sorry but fi try my best i canot understand how i can load that 20 child meshes my .obj file have and for some reason the OBJLOader2 loads only the last mesh and is not load nice.

Basicaly my .obj file is have this format:
```
group: Array [ Mesh1, Mesh2, Mesh3. MEsh4, MEsh 21]
```

## Look at my logs please 

![1](https://user-images.githubusercontent.com/20750445/38904058-cc37952a-42b0-11e8-802d-dc3a1fdaea65.PNG)

i tryit this code but is not load enythng

```typescript

// // instantiate the loader
    const OBJloader = new OBJLoader2();
    OBJloader.setPath('../../../../assets/3D_models/brain/');

    // function called on successful load
    const callbackOnLoadObj = ( event ) => {

      console.log(event);
      this.scene.add( event.detail.loaderRootNode );
      console.log(event.detail.loaderRootNode);
      console.log('Load finish');

      event.detail.loaderRootNode.traverse( (x) => {
        console.log(x);   // <===== IS NOT WORK
      });

    };

    const callbackOnMeshAlter = ( event ) => {
      console.log(event);
      // this.scene.add( event.detail.loaderRootNode );
      console.log(event.detail.loaderRootNode);
      console.log('Load finish');
    };

    const asynchromus = true;
    OBJloader.load( 'brain.obj', callbackOnLoadObj, null, null, callbackOnMeshAlter, asynchromus );


```

End i have errors 


## I ask you to load in parallel multiple .obj files because i was thinking 
> "OK the loader2 is NOT WORK WITH GROUPS maybe is work with multiple files but again the files is soo big i can do that 

if you can sow me what i missing 

thank you in advantage.

**Comment by kaisalmen** [comment] 2018-04-18 20:04
I have to admit that I don't fully understand your problem. Are you able to share your code and assets somewhere? It is hard to perform a proper analysis without the real data
Why do you expect multiple child meshes? Is your OBJ file structured like this:
```
g group1
...
g group2
...
g group3
...
```
I asked, because `OBJLoader2` only creates new meshes when a new group is declared within a file or when a face definition structure is changed.

**Comment by kaisalmen** [comment] 2018-04-19 18:40
@George35mk I think I know what is the difference to `OBJLoader` is. If only one group is defined in `brain.obj` then it will spit out one Mesh with a MultiMaterial. If you look at the single child Mesh attached the Group in the onLoad callback does this Mesh contain an array of Materials? Then you need to loop over those and apply your adjustments. Does that make sense to you? This is my best guest without having the model available

**Comment by George35mk** [comment] 2018-04-19 18:48
Hi, 
Yes the objloader have 19 geometries all the parts of the brain when i load the model  with this code

### how i can do the same with the OBJLoader2 ??
```typescript
    const objLoader: any = new OBJLoader(manager);
    // objLoader.setMaterials(materials);
    objLoader.setPath('../../../../assets/3D_models/brain/');
    objLoader.load('brain.obj', (object) => {

         object.children.forEach(child => {
          
              console.log(child);
         });

    }
```

**Comment by kaisalmen** [comment] 2018-04-19 19:19
If there is only one "g" definition in `brain.obj` then `OBJLoader2` will create one Mesh with many Materials. It behaves different then `OBJLoader`, but the behavior is according the OBJ file spec. I could introduce a flag that will create Meshes on "o" instructions in the file, but this is guess work. Can you give me access to the file? If not publicly then send me a link via email (website is in my GitHub profile). Thanks

**Comment by kaisalmen** [comment] 2018-04-19 21:07
I have created branch Issue40:
https://github.com/kaisalmen/WWOBJLoader/tree/Issue40

Use the following to enforce that "o" should be treated as Mesh descriptor.
```javascript
objLoader2.setUseOAsMesh( true );
```
I tested it with objverify:
https://github.com/kaisalmen/WWOBJLoader/blob/Issue40/test/objverify/verify.html

**Comment by Death111** [comment] 2018-04-21 09:27
Nice ;) I ran into this 'problem' aswell. But trying to load the file with Unity resulted in the same mesh. So only on "g" a new mesh is created, otherwise just multimaterial.
Did not know this aswell, but it is correct to do so. The new option is nice (did not try)

**Closed** 2018-04-21 19:50 UTC
Labels: enhancement, question

**Comment by Georgehatouts** [comment] 2018-07-18 09:51
@kaisalmen I am George35mk I can confirm you is working but only if I access the group and not the meshes one by one.

if I access the mesh over a for loop I get only the 10/20 meshes I don't know why but is true.

The only whay I can access all the childrens and run loop over this array is if I get the group instanse
this is some screanshots.

![default](https://user-images.githubusercontent.com/38488771/42873432-a8cb0922-8a87-11e8-90d9-63aa14edbe23.PNG)
![2](https://user-images.githubusercontent.com/38488771/42873437-acdfb5a8-8a87-11e8-97b4-712eb37859ad.PNG)


My code is this:

```typescript

  import * as THREE from 'three'; // I need this because I have typings
  import { LoadingManager, TextureLoader, OBJLoader2, Mesh } from 'three-full';


 // This is the root method where I start to load the .obj file.
 // the .mtl file not exist sow you gonna see later I applyMaterials one by one.
  async initTestObjloader2() {

    const manager: any = new LoadingManager();

    // Setup the texture loader
    const textureLoader = new TextureLoader(manager);




    // // instantiate the loader
    const OBJloader = new OBJLoader2();
    OBJloader.setPath('../../../../assets/3D_models/brain/');
    OBJloader.setUseOAsMesh( true );

    // function called on successful load
    const callbackOnLoadObj = ( event ) => {

      console.log(event);
      // this.scene.add( event.detail.loaderRootNode );
      // console.log(event.detail.loaderRootNode);
      console.log('Load finish');

      event.detail.loaderRootNode.traverse( (data: THREE.Mesh) => {

        if (data.type === 'Group') {
          // then apply the materials
          this.applyMaterials(data);
        }
      });

    };

    const callbackOnMeshAlter = ( event ) => {
      // console.log(event);
      // console.log(event.detail.loaderRootNode);
      console.log('Load finish');
    };

    const asynchronus = true;
    OBJloader.load( 'brain.obj', callbackOnLoadObj, null, null, callbackOnMeshAlter, asynchronus );


  }

  async applyMaterials(object) {

    const manager: any = new THREE.LoadingManager();
    const loader = new THREE.TextureLoader(manager);

    // Load the textures
    const m__cerebellum_glossy      = loader.load('../../../../assets/3D_models/brain/cerebellum_glossy.png');
    const m__cerebellum_normal_map  = loader.load('../../../../assets/3D_models/brain/cerebellum_norma.png');
    const m__cerebellum_texture     = loader.load('../../../../assets/3D_models/brain/cerebellum_texture.png');

    const m__hemi_left_bw           = loader.load('../../../../assets/3D_models/brain/hemi_left_bw.png');
    const m__hemi_left_color        = loader.load('../../../../assets/3D_models/brain/hemi_left_color.png');
    const m__hemi_left_glossy       = loader.load('../../../../assets/3D_models/brain/hemi_left_glossy.png');
    const m__hemi_left_yellow       = loader.load('../../../../assets/3D_models/brain/hemi_left_yellow.png');

    const m__hemi_right_bw          = loader.load('../../../../assets/3D_models/brain/hemi_right_bw.png');
    const m__hemi_right_color       = loader.load('../../../../assets/3D_models/brain/hemi_right_color.png');
    const m__hemi_right_glossy      = loader.load('../../../../assets/3D_models/brain/hemi_right_glossy.png');
    const m__hemi_right_yellow      = loader.load('../../../../assets/3D_models/brain/hemi_right_yellow.png');

    const m__subcortical_color      = loader.load('../../../../assets/3D_models/brain/subcortical_color.png');
    const m__subcortical_glossy     = loader.load('../../../../assets/3D_models/brain/subcortical_glossy.png');
    const m__subcortical_normal     = loader.load('../../../../assets/3D_models/brain/subcortical_normal.png');
    const m__white_color            = loader.load('../../../../assets/3D_models/brain/white_color.png');
    const m__white_glossy_map       = loader.load('../../../../assets/3D_models/brain/white_glossy.png');

    console.log(object);



    const mat_left_hemisphere = new THREE.MeshPhongMaterial({
      map: m__hemi_left_bw,
      specularMap: m__hemi_left_glossy,
    });

    const mat_right_hemisphere = new THREE.MeshPhongMaterial({
      map: m__hemi_right_bw,
      specularMap: m__hemi_right_glossy,
    });

    const mat_white_area = new THREE.MeshPhongMaterial({
      map: m__white_color,
      specularMap: m__white_glossy_map,
    });


    const mat_serebellum = new THREE.MeshPhongMaterial({
      map: m__cerebellum_texture,
      normalMap: m__cerebellum_normal_map,
      specularMap: m__cerebellum_glossy,
    });


    const mat_subcortical = new THREE.MeshPhongMaterial({
      map: m__subcortical_color,
      normalMap: m__subcortical_normal,
      specularMap: m__subcortical_glossy,
      color: 0xffffff,
      shininess: 90
    });



    const mat_default = new THREE.MeshPhongMaterial({color: 0xffffff, shininess: 90}); // { color: 0xe1e1e1 }

    object.children.forEach(child => {

      switch (child.name) {
        case 'left_cerebral_hemisphere':
          child.material = mat_right_hemisphere;
          break;

        case 'right_cerebral_hemisphere':
          child.material = mat_left_hemisphere;
          break;

        case 'white_brain':
          child.material = mat_white_area;
          break;

        case 'cerebelum':
          child.material = mat_serebellum;
          break;

        default:
          child.material = mat_subcortical;
        break;
      }


      child.castShadow = true; // default is false
      child.receiveShadow = false; // default

    });


    object.name = 'Brain_group';
    object.position.set(0, 0, 0);
    this.scene.add(object); // root object


    this.onReady.next(true);

  }

```

**Comment by kaisalmen** [comment] 2018-07-20 20:34
> if I access the mesh over a for loop I get only the 10/20 meshes I don't know why but is true.
@Georgehatouts I was wondering whether 10/20 get lost in the missing else here:
```javascript
event.detail.loaderRootNode.traverse( (data: THREE.Mesh) => {

  if (data.type === 'Group') {
    // then apply the materials
    this.applyMaterials(data);
  }
});
```
Sorry, don't have a better idea.

**Comment by George35mk** [comment] 2018-07-20 20:58
if I add this code : 
```typescript
event.detail.loaderRootNode.traverse( (data: THREE.Mesh) => {

  if (data.type === 'Mesh') {
     console.log(data);    // prints 10 meshes
     this.scene.add(data);
  }
});
```


> This will gonna add inside the scene only the 50% or 10 from 20 meshes from the file. 

but if run the code:

```typescript
event.detail.loaderRootNode.traverse( (data: THREE.Mesh) => {

  if (data.type === 'Mesh') {
     console.log(data); // prints 20 meshes
  }
});
```

> this code is gonna print  20 meshes in the console.

Yes I know is very weird.
