### ISSUE TITLE
NaN Radius in BufferGeometry problem when loading obj with many g (groups) inside

### ISSUE THREAD

**Issue by jimver04** [kaisalmen/WWOBJLoader#27] opened 2017-11-16 08:29 UTC
Congrats for the nice loader. It is very helpful. However I found a bug.

I want to load an obj model of 55MB with 20 groups inside. If I unite them as a single group ok it works. However, if they are not united into a single group then I get the following message:  THREE.BufferGeometry.computeBoundingSphere(): Computed radius is NaN. The "position" attribute is likely to have NaN values. See image below

![image](https://user-images.githubusercontent.com/1898502/32881012-5f121940-cab8-11e7-86d5-6a09ea7394a4.png)

For lighter models, .e.g 12MB with 20 groups it works nice. I guess there are some limitations on the size of each group (g) in the obj file. I like to have the model split into groups because it loads incrementally.

Here you can find the code : https://github.com/DigiArt-project/WordpressUnity3DEditor
at    js_libs/wu_webw_3d_view.js

Thanks,
Dimitrios

**Comment by kaisalmen** [comment] 2017-11-16 08:50
Hi @jimver04,
this should be resolved already with #21. However, this requires you to use V2.x.x of OBJLoader2.
V2.1.2 is now bundled with three.js R88. You can also use the npm: https://www.npmjs.com/package/wwobjloader2

The way the loader is used changed due to the merge of `OBJLoader2` and `WWOBJLoader2`, but especially this example should help making migration easy:
https://github.com/kaisalmen/WWOBJLoader/blob/master/test/wwobjloader2

Kai

**Comment by jimver04** [comment] 2017-11-16 12:50
Hi Kai,
thanks for the quick answer. I will check v88.
Thanks,
D.

**Comment by kaisalmen** [comment] 2017-11-19 22:06
I assume this is already fixed and close it. If this is not true, issue will be re-opened.

**Comment by lucantolinos** [comment] 2017-11-30 08:09
Your loader is great but I'm facing the same issue as #21 and #27
I've tested with a very huge model 350Mb and it works flawless, but on a very simple model generated with SweetHome3D (a door in a wall), I have the issue.
I've attached screenshot of the error message of the web browser (safari 11, tested too with google Chrome and have the same issue.)
I've tested with your online demo (v2.1.2) https://kaisalmen.de/wwobjloader2/wwobjloader2stage/main.min.html and with my own code on 2.2.0 and find the exactly the same issue.
You will find 2 models in the next part of this message : 
- Model that didn't work
- Model that work
The only change between the two models is the integration of the door inside the wall or in front of the wall. It's perhaps related to the problem of belonging to a group as jimver04 said ?


**Model that doesn't work (door integrated in the wall):**
The error messages :
![screen shot 2017-11-30 at 08 49 55](https://user-images.githubusercontent.com/18658010/33419674-c38b48bc-d5ab-11e7-8b8a-17a59358d5b8.png)
The display is not correct (the wall is not rendered) :
![screen shot 2017-11-30 at 08 49 48](https://user-images.githubusercontent.com/18658010/33419675-c3a71092-d5ab-11e7-96db-9e88184a28fc.png)
What it should look like : 
![screen shot 2017-11-30 at 08 50 08](https://user-images.githubusercontent.com/18658010/33419693-e5e3ee32-d5ab-11e7-8b55-da2a58cdc337.png)
The file the reproduce the problem (OBJ+MTL) : 
https://wetransfer.com/downloads/bd4620e53932a7839022222e76f2ab2b20171130075432/b5672f4f28c3b8e16cc366b4ea46cdc520171130075432/02d4e5

**The model that works (door in front of the wall) :** 
Obtained : 
![screen shot 2017-11-30 at 08 59 44](https://user-images.githubusercontent.com/18658010/33420068-7072ca54-d5ad-11e7-95a9-4bf2dd2407ec.png)
Expected : 
![screen shot 2017-11-30 at 09 05 10](https://user-images.githubusercontent.com/18658010/33420095-986b2740-d5ad-11e7-885a-6e8b831a9dbf.png)
The files (OBJ+MTL):  https://wetransfer.com/downloads/d2dabfb244276f0fc4a7ac1dcc36418c20171130080601/5b402a2409272f8102853f147358d45f20171130080601/b30da0


Hope it can help fixing the issue. 
Luc;

**Comment by kaisalmen** [comment] 2017-11-30 08:27
@lucantolinos thank you for your input. 👍 This should help me understand and then fix the problem. I will investigate.

**Comment by kaisalmen** [comment] 2017-11-30 22:13
I understood and fixed the issue. Basically, all vertex, normal and uv data has to be kept throughout the parsing. Nothing can be removed to save memory as face declarations are allowed to reference backwards across groups. The spec doesn't forbid this, so it has to be supported.

**Comment by kaisalmen** [comment] 2017-12-05 22:15
The issue is fixed, but at least another issue has been found (missing support for negative face indices). #28 should make parser behaviour validation easier.

**Closed by kaisalmen** 2017-12-05 22:15 UTC
Labels: bug

**Comment by lucantolinos** [comment] 2017-12-06 10:18
Ok, tested and it works.
Great Job !
